"""
Enterprise Execution Sandbox — REST API.

Endpoints:
  GET    /api/sandboxes                — List sandboxes
  POST   /api/sandboxes                — Create sandbox
  GET    /api/sandboxes/{id}           — Get sandbox detail
  POST   /api/sandboxes/{id}/prepare   — Prepare repository
  POST   /api/sandboxes/{id}/execute   — Execute command
  POST   /api/sandboxes/{id}/pause     — Pause sandbox
  POST   /api/sandboxes/{id}/resume    — Resume sandbox
  POST   /api/sandboxes/{id}/destroy   — Destroy sandbox
  GET    /api/sandboxes/{id}/artifacts — List artifacts
  GET    /api/sandboxes/{id}/logs      — List logs
  GET    /api/sandboxes/{id}/resources — Resource usage
"""
from __future__ import annotations

import logging

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

from backend.services.enterprise_execution_sandbox import (
    SUPPORTED_LANGUAGES,
    execution_sandbox,
)

log = logging.getLogger(__name__)
router = APIRouter(prefix="/api/sandboxes", tags=["Enterprise Sandbox"])

# ── Schemas ─────────────────────────────────────────────────────────────────

class CreateSandboxRequest(BaseModel):
    name: str
    repo_url: str = ""
    branch: str = "main"
    language: str = "python"

class ExecuteRequest(BaseModel):
    command: str = ""
    language: str = ""
    timeout: int = 300


# ── Endpoints ───────────────────────────────────────────────────────────────

@router.get("")
async def list_sandboxes(
    status: str = Query("", description="Filter by status"),
    language: str = Query("", description="Filter by language"),
):
    """List all sandboxes."""
    return {"sandboxes": await execution_sandbox.list_sandboxes(status, language)}


@router.get("/languages")
async def list_languages():
    """List supported execution languages."""
    return {"languages": SUPPORTED_LANGUAGES}


@router.post("")
async def create_sandbox(req: CreateSandboxRequest):
    """Create a new sandbox."""
    try:
        sbx = await execution_sandbox.create_sandbox(
            name=req.name,
            repo_url=req.repo_url,
            branch=req.branch,
            language=req.language,
        )
        return sbx.to_dict()
    except Exception as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@router.get("/{sandbox_id}")
async def get_sandbox(sandbox_id: str):
    """Get sandbox details."""
    sbx = await execution_sandbox.get_sandbox(sandbox_id)
    if not sbx:
        raise HTTPException(status_code=404, detail=f"Sandbox not found: {sandbox_id}")
    return sbx.to_dict()


@router.post("/{sandbox_id}/prepare")
async def prepare_repository(sandbox_id: str):
    """Prepare repository inside sandbox (clone, deps, env)."""
    sbx = await execution_sandbox.prepare_repository(sandbox_id)
    if not sbx:
        raise HTTPException(status_code=404, detail=f"Sandbox not found: {sandbox_id}")
    return sbx.to_dict()


@router.post("/{sandbox_id}/execute")
async def execute_command(sandbox_id: str, req: ExecuteRequest):
    """Execute a command inside the sandbox."""
    result = await execution_sandbox.execute(
        sandbox_id=sandbox_id,
        command=req.command,
        language=req.language,
        timeout=req.timeout,
    )
    if not result:
        sbx = await execution_sandbox.get_sandbox(sandbox_id)
        if not sbx:
            raise HTTPException(status_code=404, detail=f"Sandbox not found: {sandbox_id}")
        raise HTTPException(status_code=409, detail=f"Sandbox is in status: {sbx.status}")
    return result.to_dict()


@router.post("/{sandbox_id}/pause")
async def pause_sandbox(sandbox_id: str):
    """Pause a running sandbox."""
    sbx = await execution_sandbox.pause_sandbox(sandbox_id)
    if not sbx:
        raise HTTPException(status_code=409, detail="Sandbox not found or not running")
    return sbx.to_dict()


@router.post("/{sandbox_id}/resume")
async def resume_sandbox(sandbox_id: str):
    """Resume a paused sandbox."""
    sbx = await execution_sandbox.resume_sandbox(sandbox_id)
    if not sbx:
        raise HTTPException(status_code=409, detail="Sandbox not found or not paused")
    return sbx.to_dict()


@router.post("/{sandbox_id}/destroy")
async def destroy_sandbox(sandbox_id: str):
    """Destroy a sandbox (preserves artifacts)."""
    sbx = await execution_sandbox.destroy_sandbox(sandbox_id)
    if not sbx:
        raise HTTPException(status_code=404, detail=f"Sandbox not found: {sandbox_id}")
    return sbx.to_dict()


@router.get("/{sandbox_id}/artifacts")
async def get_artifacts(sandbox_id: str):
    """List artifacts generated by a sandbox."""
    artifacts = await execution_sandbox.get_artifacts(sandbox_id)
    return {"artifacts": artifacts}


@router.get("/{sandbox_id}/logs")
async def get_logs(sandbox_id: str):
    """List execution logs for a sandbox."""
    logs = await execution_sandbox.get_logs(sandbox_id)
    return {"logs": logs}


@router.get("/{sandbox_id}/resources")
async def get_resources(sandbox_id: str):
    """Get current resource usage for a sandbox."""
    usage = await execution_sandbox.get_resource_usage(sandbox_id)
    if usage is None:
        raise HTTPException(status_code=404, detail=f"Sandbox not found: {sandbox_id}")
    return usage
