"""The Workflow domain: pure, no I/O, no framework.

    status      the lifecycle from draft through compiled to approved
    nodes       nodes, conditions, edges, retries and timeouts
    parallel    fan-outs, compensations and resume points
    graph       the DAG, reachability, independence and the critical path
    workflow    the aggregate and its digest
    policy      whether the graph is advisable, reporting every reason
"""

from backend.contexts.workflow.domain.errors import (
    BranchTooNarrow,
    BranchWithoutDefault,
    CompensationTargetInvalid,
    ConditionNotUpstream,
    CyclicWorkflow,
    DanglingEdge,
    DigestMismatch,
    DigestNotComputed,
    DuplicateNode,
    DuplicateWorkflow,
    IllegalWorkflowTransition,
    IncompleteWorkflow,
    InvalidIdentifier,
    ParallelGroupTooSmall,
    ParallelMembersDependent,
    ResumePointInsideGroup,
    RetryWithoutIdempotency,
    TaskInvented,
    TaskNotCovered,
    TimeoutUnsatisfiable,
    UnknownNode,
    UnreachableNode,
    WorkflowApproved as WorkflowApprovedError,
    WorkflowError,
    WorkflowIsSuperseded,
    WorkflowNotFound,
    WorkflowRefused,
)
from backend.contexts.workflow.domain.events import (
    AGGREGATE_TYPE,
    WORKFLOW_EVENT_TYPES,
    BranchCreated,
    NodeAdded,
    ParallelGroupCreated,
    WorkflowApproved,
    WorkflowCompiled,
    WorkflowCreated,
    WorkflowValidated,
    WorkflowVersioned,
)
from backend.contexts.workflow.domain.factory import (
    arm,
    branch_node,
    compensation,
    compensation_node,
    compile_from_plan,
    edge,
    parallel_group,
    resume_point,
    retry,
    task_node,
    timeout,
)
from backend.contexts.workflow.domain.graph import WorkflowGraph
from backend.contexts.workflow.domain.identifiers import (
    GroupId,
    WorkflowId,
    normalise_node_id,
)
from backend.contexts.workflow.domain.nodes import (
    BackoffKind,
    BranchArm,
    ConditionKind,
    EdgeKind,
    NodeKind,
    WorkflowCondition,
    WorkflowEdge,
    WorkflowNode,
    WorkflowRetryPolicy,
    WorkflowTimeout,
)
from backend.contexts.workflow.domain.parallel import (
    JoinPolicy,
    ResumePoint,
    WorkflowCompensation,
    WorkflowParallelGroup,
)
from backend.contexts.workflow.domain.policy import (
    LONG_WORKFLOW_NODES,
    SPOF_RATIO,
    PolicyFinding,
    PolicyReport,
    Severity,
    WorkflowPolicy,
    default_policy,
)
from backend.contexts.workflow.domain.status import (
    STATUS_TRANSITIONS,
    TERMINAL_STATUSES,
    WorkflowStatus,
    is_legal_transition,
    permitted_from,
    refusal_reason,
)
from backend.contexts.workflow.domain.workflow import (
    ARTIFACT_KIND,
    CANONICAL_FORM_VERSION,
    GOVERNED_FIELDS,
    REQUIRED_ELEMENTS,
    Workflow,
)

__all__ = [
    "Workflow",
    "WorkflowStatus",
    "STATUS_TRANSITIONS",
    "TERMINAL_STATUSES",
    "is_legal_transition",
    "permitted_from",
    "refusal_reason",
    "WorkflowId",
    "GroupId",
    "normalise_node_id",
    "WorkflowNode",
    "NodeKind",
    "WorkflowEdge",
    "EdgeKind",
    "WorkflowCondition",
    "ConditionKind",
    "BranchArm",
    "WorkflowRetryPolicy",
    "BackoffKind",
    "WorkflowTimeout",
    "WorkflowParallelGroup",
    "JoinPolicy",
    "WorkflowCompensation",
    "ResumePoint",
    "WorkflowGraph",
    "WorkflowPolicy",
    "PolicyReport",
    "PolicyFinding",
    "Severity",
    "default_policy",
    "SPOF_RATIO",
    "LONG_WORKFLOW_NODES",
    "ARTIFACT_KIND",
    "CANONICAL_FORM_VERSION",
    "GOVERNED_FIELDS",
    "REQUIRED_ELEMENTS",
    "compile_from_plan",
    "task_node",
    "branch_node",
    "compensation_node",
    "edge",
    "arm",
    "retry",
    "timeout",
    "parallel_group",
    "compensation",
    "resume_point",
    "AGGREGATE_TYPE",
    "WorkflowCreated",
    "WorkflowValidated",
    "WorkflowCompiled",
    "WorkflowApproved",
    "WorkflowVersioned",
    "NodeAdded",
    "BranchCreated",
    "ParallelGroupCreated",
    "WORKFLOW_EVENT_TYPES",
    "WorkflowError",
    "InvalidIdentifier",
    "IllegalWorkflowTransition",
    "WorkflowApprovedError",
    "WorkflowIsSuperseded",
    "CyclicWorkflow",
    "UnreachableNode",
    "DanglingEdge",
    "DuplicateNode",
    "UnknownNode",
    "TaskNotCovered",
    "TaskInvented",
    "ConditionNotUpstream",
    "BranchWithoutDefault",
    "BranchTooNarrow",
    "ParallelMembersDependent",
    "ParallelGroupTooSmall",
    "RetryWithoutIdempotency",
    "CompensationTargetInvalid",
    "TimeoutUnsatisfiable",
    "ResumePointInsideGroup",
    "IncompleteWorkflow",
    "WorkflowRefused",
    "DigestMismatch",
    "DigestNotComputed",
    "WorkflowNotFound",
    "DuplicateWorkflow",
]
