apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortexprime.fullname" . }}-backend
  labels:
    {{- include "cortexprime.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "cortexprime.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
