"""The Execution Runtime domain: pure, no I/O, no framework, no workers.

    state       the run's state machine and the node's
    worker      what a worker must be -- a Protocol, never an implementation
    lease       leases, attempts, and one node's runtime state
    checkpoint  the positions a run can be resumed from
    execution   the aggregate and its digest
    policy      whether a move is advisable, reporting every reason
"""

from backend.contexts.execution.domain.bound_capability import (
    BindingRefused,
    BoundCapability,
)
from backend.contexts.execution.domain.worker_contract import (
    CancellationSupport,
    WorkerExecutionRequest,
    WorkerExecutionResult,
    WorkerOutcome,
)
from backend.contexts.execution.domain.compensation import (
    COMPENSATION_TRANSITIONS,
    CompensationRecord,
    CompensationState,
)
from backend.contexts.execution.domain.effects import (
    DeliverySemantics,
    EffectProfile,
    EffectSemantics,
    profile_for,
)
from backend.contexts.execution.domain.failure import FailureClass, FailureRecord
from backend.contexts.execution.domain.idempotency import (
    IdempotencyKey,
    IdempotencyRecord,
    IdempotencyStatus,
    derive_key,
)
from backend.contexts.execution.domain.recovery import (
    RecoveryAction,
    RecoveryDecision,
    RecoveryTrigger,
    plan_recovery,
)
from backend.contexts.execution.domain.retry import (
    DEFAULT_RETRY_POLICY,
    BackoffKind,
    RetryDecision,
    RetryPolicy,
    RetryVerdict,
    decide_retry,
)
from backend.contexts.execution.domain.checkpoint import (
    CHECKPOINT_KIND,
    ExecutionCheckpoint,
)
from backend.contexts.execution.domain.errors import (
    RetryRefused,
    AmbiguousRetry,
    AttemptsExhausted,
    CheckpointAhead,
    DependenciesUnsatisfied,
    DigestMismatch,
    DigestNotComputed,
    DuplicateExecution,
    ExecutionError,
    ExecutionFinished,
    ExecutionNotFound,
    ExecutionRefused,
    IllegalExecutionTransition,
    IllegalNodeTransition,
    IncompleteExecution,
    InvalidIdentifier,
    LeaseExpired,
    LeaseNotHeld,
    NoCheckpoint,
    NodeAlreadyLeased,
    NodeNotRunning,
    UnknownNode,
    UnknownWorker,
    WorkerCannotRun,
)
from backend.contexts.execution.domain.events import (
    AGGREGATE_TYPE,
    EXECUTION_EVENT_TYPES,
    ExecutionAssigned,
    ExecutionCancelled,
    ExecutionCheckpointCreated,
    ExecutionCompleted,
    ExecutionFailed,
    ExecutionPaused,
    ExecutionResumed,
    ExecutionRetried,
    ExecutionStarted,
    ExecutionTimedOut,
)
from backend.contexts.execution.domain.execution import (
    ARTIFACT_KIND,
    CANONICAL_FORM_VERSION,
    GOVERNED_FIELDS,
    Execution,
)
from backend.contexts.execution.domain.factory import node_spec, start_run, worker
from backend.contexts.execution.domain.identifiers import (
    AttemptId,
    CheckpointId,
    ExecutionId,
    LeaseId,
    WorkerId,
    normalise_node_id,
)
from backend.contexts.execution.domain.lease import (
    ExecutionAttempt,
    ExecutionLease,
    NodeRun,
    NodeSpec,
)
from backend.contexts.execution.domain.policy import (
    ExecutionPolicy,
    PolicyFinding,
    PolicyReport,
    Severity,
    default_policy,
)
from backend.contexts.execution.domain.state import (
    EXECUTION_TRANSITIONS,
    NODE_TRANSITIONS,
    TERMINAL_STATES,
    ExecutionState,
    NodeState,
    execution_permitted_from,
    execution_refusal_reason,
    is_legal_execution_transition,
    is_legal_node_transition,
    node_permitted_from,
    published_status_of,
)
from backend.contexts.execution.domain.worker import (
    ExecutionWorker,
    RunContext,
    WorkerHealth,
    WorkerKind,
    WorkerRegistration,
)

__all__ = [
    "BoundCapability",
    "BindingRefused",
    "WorkerOutcome",
    "WorkerExecutionRequest",
    "WorkerExecutionResult",
    "CancellationSupport",

    "FailureClass",
    "FailureRecord",
    "EffectSemantics",
    "DeliverySemantics",
    "EffectProfile",
    "profile_for",
    "RetryVerdict",
    "BackoffKind",
    "RetryPolicy",
    "RetryDecision",
    "decide_retry",
    "DEFAULT_RETRY_POLICY",
    "IdempotencyStatus",
    "IdempotencyKey",
    "IdempotencyRecord",
    "derive_key",
    "RecoveryAction",
    "RecoveryTrigger",
    "RecoveryDecision",
    "plan_recovery",
    "CompensationState",
    "CompensationRecord",
    "COMPENSATION_TRANSITIONS",
    "RetryRefused",

    "Execution",
    "ExecutionState",
    "NodeState",
    "EXECUTION_TRANSITIONS",
    "NODE_TRANSITIONS",
    "TERMINAL_STATES",
    "is_legal_execution_transition",
    "is_legal_node_transition",
    "execution_permitted_from",
    "node_permitted_from",
    "execution_refusal_reason",
    "published_status_of",
    "ExecutionId",
    "AttemptId",
    "LeaseId",
    "CheckpointId",
    "WorkerId",
    "normalise_node_id",
    "NodeSpec",
    "NodeRun",
    "ExecutionLease",
    "ExecutionAttempt",
    "ExecutionCheckpoint",
    "CHECKPOINT_KIND",
    "ExecutionWorker",
    "WorkerRegistration",
    "WorkerKind",
    "WorkerHealth",
    "RunContext",
    "ExecutionPolicy",
    "PolicyReport",
    "PolicyFinding",
    "Severity",
    "default_policy",
    "ARTIFACT_KIND",
    "CANONICAL_FORM_VERSION",
    "GOVERNED_FIELDS",
    "start_run",
    "node_spec",
    "worker",
    "AGGREGATE_TYPE",
    "ExecutionStarted",
    "ExecutionAssigned",
    "ExecutionCheckpointCreated",
    "ExecutionPaused",
    "ExecutionResumed",
    "ExecutionCompleted",
    "ExecutionFailed",
    "ExecutionCancelled",
    "ExecutionTimedOut",
    "ExecutionRetried",
    "EXECUTION_EVENT_TYPES",
    "ExecutionError",
    "InvalidIdentifier",
    "IllegalExecutionTransition",
    "IllegalNodeTransition",
    "ExecutionFinished",
    "UnknownNode",
    "DependenciesUnsatisfied",
    "NodeNotRunning",
    "LeaseNotHeld",
    "LeaseExpired",
    "NodeAlreadyLeased",
    "AttemptsExhausted",
    "AmbiguousRetry",
    "IncompleteExecution",
    "NoCheckpoint",
    "CheckpointAhead",
    "UnknownWorker",
    "WorkerCannotRun",
    "ExecutionRefused",
    "DigestMismatch",
    "DigestNotComputed",
    "ExecutionNotFound",
    "DuplicateExecution",
]
