"use client";

import {
  ArrowUpRight,
  Cpu,
  Shield,
  Settings,
} from "lucide-react";

import Card from "@/components/ui/Card";
import SectionHeader from "@/components/ui/SectionHeader";

const recommendationItems = [
  {
    id: "process-improvements",
    label: "Process Improvements",
    icon: ArrowUpRight,
    color: "text-[#6366F1]",
  },
  {
    id: "capability-improvements",
    label: "Capability Improvements",
    icon: Cpu,
    color: "text-[#F59E0B]",
  },
  {
    id: "policy-improvements",
    label: "Policy Improvements",
    icon: Shield,
    color: "text-[#EF4444]",
  },
  {
    id: "operational-improvements",
    label: "Operational Improvements",
    icon: Settings,
    color: "text-[#38B88A]",
  },
];

export default function Recommendations() {
  return (
    <section>
      <SectionHeader
        title="Recommendations"
        subtitle="Actionable improvements generated by the learning engine"
      />
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {recommendationItems.map((item) => (
          <Card key={item.id} className="p-5">
            <div className="mb-3 flex items-center gap-3">
              <div className="rounded-lg bg-[#F9FAFB] p-2 text-[#6B7280]">
                <item.icon className="h-4 w-4" />
              </div>
              <span className="text-sm font-medium text-[#6B7280]">
                {item.label}
              </span>
            </div>
            <p className="text-sm text-[#D1D5DB]">No recommendations.</p>
          </Card>
        ))}
      </div>
    </section>
  );
}
