"""Descriptive metadata: how the intent is labelled and where it came from.

``origin`` is the field that earns its place. An intent typed by a human at 3am
during an incident and one generated by a scheduled review are held to different
standards -- and telling them apart later is impossible unless it was recorded at
the time.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, Sequence

from backend.contracts._contract import Contract
from backend.contracts.errors import ContractViolation

__all__ = ["IntentOrigin", "IntentMetadata"]


class IntentOrigin(str, Enum):
    """Where the intent came from."""

    HUMAN = "human"
    SCHEDULED = "scheduled"
    ESCALATION = "escalation"
    DERIVED = "derived"

    @property
    def is_human_authored(self) -> bool:
        return self is IntentOrigin.HUMAN

    @property
    def needs_stronger_review(self) -> bool:
        """Whether this origin warrants a closer look before approval.

        ``DERIVED`` -- an intent CortexPrime generated from another intent or a
        detected condition -- has no human who chose the words. That is exactly
        when an under-specified mandate is most likely to pass unnoticed, because
        there is nobody to be embarrassed by it.
        """
        return self is IntentOrigin.DERIVED


@dataclass(frozen=True)
class IntentMetadata(Contract):
    """Labels and provenance. Carries no part of the mandate itself."""

    CONTRACT_NAME = "cortexprime.intent.metadata"

    title: str
    origin: IntentOrigin = IntentOrigin.HUMAN
    tags: frozenset = field(default_factory=frozenset)
    requested_for: Optional[str] = None
    derived_from: Optional[str] = None

    def __post_init__(self) -> None:
        if not isinstance(self.title, str) or not self.title.strip():
            raise ContractViolation("an intent must have a title")
        if not isinstance(self.origin, IntentOrigin):
            raise ContractViolation("origin must be an IntentOrigin")
        if not isinstance(self.tags, (frozenset, set)):
            raise ContractViolation("tags must be a set")
        for tag in self.tags:
            if not isinstance(tag, str) or not tag.strip():
                raise ContractViolation("tags contains a blank entry")
        object.__setattr__(self, "tags", frozenset(t.strip() for t in self.tags))

        for label in ("requested_for", "derived_from"):
            value = getattr(self, label)
            if value is not None and not value.strip():
                raise ContractViolation(f"{label} must be non-blank when given")

        # A derived intent has to say what it came from, or its provenance is a
        # claim with nothing behind it.
        if self.origin is IntentOrigin.DERIVED and not self.derived_from:
            raise ContractViolation(
                "a derived intent must name what it was derived from; provenance "
                "with nothing behind it is worse than none"
            )

    @classmethod
    def create(
        cls,
        title: str,
        *,
        origin: IntentOrigin = IntentOrigin.HUMAN,
        tags: Sequence[str] = (),
        requested_for: Optional[str] = None,
        derived_from: Optional[str] = None,
    ) -> "IntentMetadata":
        return cls(
            title=title,
            origin=origin,
            tags=frozenset(tags),
            requested_for=requested_for,
            derived_from=derived_from,
        )
