"""ImplementationRecord domain: changes, claims, outcomes, and the record itself.

Pure. No I/O, no persistence, no framework.
"""

from backend.contexts.implementation_record.domain.changes import (
    ChangedFile,
    ChangeKind,
    CodeChangeSet,
)
from backend.contexts.implementation_record.domain.claims import (
    AssumptionOutcome,
    AssumptionResolution,
    Claim,
    ClaimType,
    CriterionCoverage,
    EvidenceRef,
    RiskDeclaration,
    RiskLevel,
)
from backend.contexts.implementation_record.domain.errors import (
    AssumptionAlreadyResolved,
    ClaimWithoutEvidence,
    DigestMismatch,
    DigestNotComputed,
    DuplicateClaim,
    DuplicateRecord,
    ImplementationError,
    IncompleteRecord,
    InvalidIdentifier,
    OutsideBlastRadius,
    RecordCompleted,
    RecordNotFound,
    RecordNotStarted,
    RecordSuperseded,
    UnknownAssumption,
    UnknownClaim,
)
from backend.contexts.implementation_record.domain.events import (
    IMPLEMENTATION_EVENT_TYPES,
    AssumptionResolved,
    ClaimAdded,
    DigestComputed,
    ImplementationCompleted,
    ImplementationStarted,
    ImplementationSuperseded,
    ImplementationUpdated,
    RiskDeclared,
)
from backend.contexts.implementation_record.domain.factory import (
    build,
    changed,
    claim,
    coverage,
    resolution,
    risk,
    start_implementation,
    test_run,
)
from backend.contexts.implementation_record.domain.identifiers import (
    ClaimId,
    ImplementationId,
    RiskId,
)
from backend.contexts.implementation_record.domain.outcomes import (
    BuildResult,
    ExecutionStatus,
    TestExecution,
)
from backend.contexts.implementation_record.domain.paths import (
    BlastRadiusScope,
    PathPattern,
    normalise_path,
)
from backend.contexts.implementation_record.domain.policy import (
    CompletionPolicy,
    PolicyFinding,
    PolicyReport,
    Severity,
    default_policy,
)
from backend.contexts.implementation_record.domain.record import (
    ARTIFACT_KIND,
    CANONICAL_FORM_VERSION,
    GOVERNED_FIELDS,
    ImplementationRecord,
    ImplementationStatus,
)

__all__ = [
    "ImplementationRecord",
    "ImplementationStatus",
    "ImplementationId",
    "ClaimId",
    "RiskId",
    "CodeChangeSet",
    "ChangedFile",
    "ChangeKind",
    "Claim",
    "ClaimType",
    "EvidenceRef",
    "CriterionCoverage",
    "AssumptionResolution",
    "AssumptionOutcome",
    "RiskDeclaration",
    "RiskLevel",
    "TestExecution",
    "BuildResult",
    "ExecutionStatus",
    "BlastRadiusScope",
    "PathPattern",
    "normalise_path",
    "CompletionPolicy",
    "PolicyReport",
    "PolicyFinding",
    "Severity",
    "default_policy",
    "ARTIFACT_KIND",
    "CANONICAL_FORM_VERSION",
    "GOVERNED_FIELDS",
    "start_implementation",
    "changed",
    "claim",
    "resolution",
    "risk",
    "coverage",
    "test_run",
    "build",
    "ImplementationStarted",
    "ImplementationUpdated",
    "ImplementationCompleted",
    "ClaimAdded",
    "RiskDeclared",
    "AssumptionResolved",
    "DigestComputed",
    "ImplementationSuperseded",
    "IMPLEMENTATION_EVENT_TYPES",
    "ImplementationError",
    "InvalidIdentifier",
    "OutsideBlastRadius",
    "ClaimWithoutEvidence",
    "RecordCompleted",
    "RecordNotStarted",
    "RecordSuperseded",
    "DuplicateClaim",
    "UnknownClaim",
    "AssumptionAlreadyResolved",
    "UnknownAssumption",
    "IncompleteRecord",
    "DigestMismatch",
    "DigestNotComputed",
    "RecordNotFound",
    "DuplicateRecord",
]
