import type { ScenarioId, ScenarioService, ValidationCheckpoint, ScenarioResult } from "./types"

export interface ScenarioDefinition {
  id: ScenarioId
  title: string
  goal: string
  services: Omit<ScenarioService, "durationMs" | "status">[]
  checkpointDefinitions: {
    id: string
    dimension: ValidationCheckpoint["dimension"]
    description: string
    required: boolean
  }[]
}

const checkpointDefs = {
  lifecycleInit: { id: "lifecycle-init", dimension: "mission_lifecycle" as const, description: "Mission initializes with correct goal and status", required: true },
  lifecyclePlan: { id: "lifecycle-plan", dimension: "mission_lifecycle" as const, description: "Planning stage completes with task decomposition", required: true },
  lifecycleExecute: { id: "lifecycle-execute", dimension: "mission_lifecycle" as const, description: "Execution stage runs all assigned tasks", required: true },
  lifecycleComplete: { id: "lifecycle-complete", dimension: "mission_lifecycle" as const, description: "Mission reaches completed status", required: true },
  aiDecisions: { id: "ai-decisions", dimension: "ai_decisions" as const, description: "AI reasoning traces are recorded for each stage", required: true },
  aiConfidence: { id: "ai-confidence", dimension: "ai_decisions" as const, description: "Decision confidence scores meet threshold", required: false },
  agentAssignment: { id: "agent-assignment", dimension: "agent_coordination" as const, description: "Agents are correctly assigned to stages", required: true },
  agentCompletion: { id: "agent-completion", dimension: "agent_coordination" as const, description: "All assigned agents complete their tasks", required: true },
  agentDelegation: { id: "agent-delegation", dimension: "agent_coordination" as const, description: "Agent delegation chain is recorded", required: false },
  knowledgeSearch: { id: "knowledge-search", dimension: "knowledge_retrieval" as const, description: "Knowledge base is searched for relevant context", required: false },
  knowledgeIndex: { id: "knowledge-index", dimension: "knowledge_retrieval" as const, description: "Mission results are indexed to knowledge base", required: false },
  learningUpdate: { id: "learning-update", dimension: "learning_updates" as const, description: "Learning insights are generated from mission outcome", required: false },
  governanceCheck: { id: "governance-check", dimension: "governance" as const, description: "Governance policies are evaluated", required: true },
  governanceApproval: { id: "governance-approval", dimension: "governance" as const, description: "Required approvals are obtained", required: true },
  governanceAudit: { id: "governance-audit", dimension: "governance" as const, description: "Audit trail is recorded", required: false },
  taskExecution: { id: "task-execution", dimension: "execution" as const, description: "All tasks execute successfully", required: true },
  taskErrorHandling: { id: "task-error-handling", dimension: "execution" as const, description: "Errors are properly handled and reported", required: false },
  connectorIntegration: { id: "connector-integration", dimension: "connector_execution" as const, description: "Connector integrates with external service", required: true },
  connectorDataFlow: { id: "connector-data-flow", dimension: "connector_execution" as const, description: "Data flows correctly through connector", required: false },
  artifactGeneration: { id: "artifact-generation", dimension: "artifacts" as const, description: "Artifacts are produced during execution", required: true },
  artifactStorage: { id: "artifact-storage", dimension: "artifacts" as const, description: "Artifacts are stored and accessible", required: false },
  replayCapture: { id: "replay-capture", dimension: "replay" as const, description: "Replay data captures all events", required: true },
  replayPlayback: { id: "replay-playback", dimension: "replay" as const, description: "Replay can be played back sequentially", required: false },
  timelineOrder: { id: "timeline-order", dimension: "timeline" as const, description: "Timeline events are in correct chronological order", required: true },
  timelineCompleteness: { id: "timeline-completeness", dimension: "timeline" as const, description: "Timeline includes all key events", required: false },
  metricsCollected: { id: "metrics-collected", dimension: "metrics" as const, description: "Performance metrics are collected", required: true },
  metricsThresholds: { id: "metrics-thresholds", dimension: "metrics" as const, description: "Metrics meet defined thresholds", required: false },
}

export const SCENARIO_DEFINITIONS: ScenarioDefinition[] = [
  {
    id: "deploy-service",
    title: "Deploy Service",
    goal: "Deploy frontend service v2.1.0 to production Kubernetes cluster",
    services: [
      { name: "GitHub", actions: ["Checkout source code", "Trigger CI pipeline", "Tag release v2.1.0"] },
      { name: "Docker", actions: ["Build container image", "Push to registry", "Tag as latest"] },
      { name: "Kubernetes", actions: ["Apply deployment manifest", "Rollout status check", "Verify pod health"] },
      { name: "Replay", actions: ["Capture deploy events", "Timeline reconstruction"] },
    ],
    checkpointDefinitions: [
      checkpointDefs.lifecycleInit,
      checkpointDefs.lifecyclePlan,
      checkpointDefs.lifecycleExecute,
      checkpointDefs.lifecycleComplete,
      checkpointDefs.aiDecisions,
      checkpointDefs.agentAssignment,
      checkpointDefs.agentCompletion,
      checkpointDefs.connectorIntegration,
      checkpointDefs.connectorDataFlow,
      checkpointDefs.taskExecution,
      checkpointDefs.artifactGeneration,
      checkpointDefs.artifactStorage,
      checkpointDefs.replayCapture,
      checkpointDefs.replayPlayback,
      checkpointDefs.timelineOrder,
      checkpointDefs.timelineCompleteness,
      checkpointDefs.metricsCollected,
      checkpointDefs.governanceCheck,
      checkpointDefs.governanceApproval,
    ],
  },
  {
    id: "production-incident",
    title: "Production Incident Response",
    goal: "Respond to production incident — high CPU usage detected on API servers",
    services: [
      { name: "Prometheus", actions: ["Alert triggered: HighCPUUsage", "Alert severity evaluation", "Metrics query"] },
      { name: "Grafana", actions: ["Open relevant dashboard", "Visualize CPU metrics", "Annotate incident"] },
      { name: "GitHub", actions: ["Create incident issue", "Assign incident commander", "Link to runbook"] },
      { name: "Jira", actions: ["Create incident ticket", "Set priority as Critical", "Assign to SRE team"] },
      { name: "Slack", actions: ["Post alert to #ops channel", "Notify on-call engineer", "Post incident update"] },
    ],
    checkpointDefinitions: [
      checkpointDefs.lifecycleInit,
      checkpointDefs.lifecyclePlan,
      checkpointDefs.lifecycleExecute,
      checkpointDefs.lifecycleComplete,
      checkpointDefs.aiDecisions,
      checkpointDefs.aiConfidence,
      checkpointDefs.agentAssignment,
      checkpointDefs.agentCompletion,
      checkpointDefs.agentDelegation,
      checkpointDefs.connectorIntegration,
      checkpointDefs.connectorDataFlow,
      checkpointDefs.taskExecution,
      checkpointDefs.taskErrorHandling,
      checkpointDefs.artifactGeneration,
      checkpointDefs.replayCapture,
      checkpointDefs.timelineOrder,
      checkpointDefs.metricsCollected,
      checkpointDefs.governanceCheck,
      checkpointDefs.governanceAudit,
    ],
  },
  {
    id: "security-review",
    title: "Security Review",
    goal: "Run quarterly security review across all active deployments and dependencies",
    services: [
      { name: "Security Agent", actions: ["Scan active deployments", "Check dependency CVEs", "Generate security report"] },
      { name: "Compliance Agent", actions: ["Run compliance checks", "Check policy adherence", "Flag violations"] },
      { name: "Knowledge", actions: ["Store scan results", "Index findings", "Link to prior reviews"] },
      { name: "Governance", actions: ["Evaluate policies", "Record audit trail", "Generate compliance score"] },
    ],
    checkpointDefinitions: [
      checkpointDefs.lifecycleInit,
      checkpointDefs.lifecyclePlan,
      checkpointDefs.lifecycleExecute,
      checkpointDefs.lifecycleComplete,
      checkpointDefs.aiDecisions,
      checkpointDefs.aiConfidence,
      checkpointDefs.agentAssignment,
      checkpointDefs.agentCompletion,
      checkpointDefs.knowledgeSearch,
      checkpointDefs.knowledgeIndex,
      checkpointDefs.learningUpdate,
      checkpointDefs.governanceCheck,
      checkpointDefs.governanceApproval,
      checkpointDefs.governanceAudit,
      checkpointDefs.taskExecution,
      checkpointDefs.artifactGeneration,
      checkpointDefs.artifactStorage,
      checkpointDefs.replayCapture,
      checkpointDefs.timelineOrder,
      checkpointDefs.timelineCompleteness,
      checkpointDefs.metricsCollected,
    ],
  },
  {
    id: "release-management",
    title: "Release Management",
    goal: "Release v3.0.0 with canary deployment, monitoring, and automated rollback capability",
    services: [
      { name: "Planner", actions: ["Create release plan", "Define canary strategy", "Set success criteria"] },
      { name: "Execution", actions: ["Build release artifacts", "Run migration tasks", "Coordinate deployment"] },
      { name: "Docker", actions: ["Build production images", "Tag with version", "Push to registry"] },
      { name: "Kubernetes", actions: ["Apply canary deployment", "Monitor canary health", "Scale to full rollout"] },
      { name: "Rollback", actions: ["Define rollback triggers", "Execute rollback on failure", "Verify pre-release state"] },
    ],
    checkpointDefinitions: [
      checkpointDefs.lifecycleInit,
      checkpointDefs.lifecyclePlan,
      checkpointDefs.lifecycleExecute,
      checkpointDefs.lifecycleComplete,
      checkpointDefs.aiDecisions,
      checkpointDefs.aiConfidence,
      checkpointDefs.agentAssignment,
      checkpointDefs.agentCompletion,
      checkpointDefs.agentDelegation,
      checkpointDefs.connectorIntegration,
      checkpointDefs.connectorDataFlow,
      checkpointDefs.taskExecution,
      checkpointDefs.taskErrorHandling,
      checkpointDefs.artifactGeneration,
      checkpointDefs.artifactStorage,
      checkpointDefs.replayCapture,
      checkpointDefs.replayPlayback,
      checkpointDefs.timelineOrder,
      checkpointDefs.timelineCompleteness,
      checkpointDefs.metricsCollected,
      checkpointDefs.metricsThresholds,
      checkpointDefs.governanceCheck,
      checkpointDefs.governanceApproval,
    ],
  },
  {
    id: "mission-recovery",
    title: "Mission Recovery",
    goal: "Recover mission execution after catastrophic runtime failure",
    services: [
      { name: "Replay", actions: ["Analyze failure point in timeline", "Identify root cause"] },
      { name: "Knowledge", actions: ["Search for similar failures", "Retrieve recovery procedures"] },
      { name: "Governance", actions: ["Evaluate recovery plan", "Approve recovery execution"] },
    ],
    checkpointDefinitions: [
      checkpointDefs.lifecycleInit,
      checkpointDefs.lifecyclePlan,
      checkpointDefs.lifecycleExecute,
      checkpointDefs.lifecycleComplete,
      checkpointDefs.aiDecisions,
      checkpointDefs.aiConfidence,
      checkpointDefs.agentAssignment,
      checkpointDefs.agentCompletion,
      checkpointDefs.knowledgeSearch,
      checkpointDefs.knowledgeIndex,
      checkpointDefs.learningUpdate,
      checkpointDefs.governanceCheck,
      checkpointDefs.governanceApproval,
      checkpointDefs.governanceAudit,
      checkpointDefs.taskExecution,
      checkpointDefs.taskErrorHandling,
      checkpointDefs.replayCapture,
      checkpointDefs.replayPlayback,
      checkpointDefs.timelineOrder,
      checkpointDefs.timelineCompleteness,
      checkpointDefs.metricsCollected,
      checkpointDefs.metricsThresholds,
    ],
  },
]

export function getScenarioDefinition(id: ScenarioId): ScenarioDefinition | undefined {
  return SCENARIO_DEFINITIONS.find((s) => s.id === id)
}

export function getAllScenarioIds(): ScenarioId[] {
  return SCENARIO_DEFINITIONS.map((s) => s.id)
}
