export const queryKeys = {
    runtime: {
        all:        ["runtime"] as const,
        status:     () => [...queryKeys.runtime.all, "status"] as const,
        health:     () => [...queryKeys.runtime.all, "health"] as const,
        agents:     () => [...queryKeys.runtime.all, "agents"] as const,
        events:     () => [...queryKeys.runtime.all, "events"] as const,
        embedding:  () => [...queryKeys.runtime.all, "embedding"] as const,
    },
    missions: {
        all:         ["missions"] as const,
        active:      () => [...queryKeys.missions.all, "active"] as const,
        completed:   () => [...queryKeys.missions.all, "completed"] as const,
        detail:      (id: string) => [...queryKeys.missions.all, "detail", id] as const,
    },
    agents: {
        all:         ["agents"] as const,
        detail:      (id: string) => [...queryKeys.agents.all, "detail", id] as const,
        logs:        (id: string) => [...queryKeys.agents.all, "logs", id] as const,
    },
    voice: {
        all:         ["voice"] as const,
        status:      () => [...queryKeys.voice.all, "status"] as const,
        sessions:    () => [...queryKeys.voice.all, "sessions"] as const,
    },
    memory: {
        all:         ["memory"] as const,
        search:      (query: string) => [...queryKeys.memory.all, "search", query] as const,
        embeddings:  () => [...queryKeys.memory.all, "embeddings"] as const,
    },
    research: {
        all:         ["research"] as const,
        results:     (id: string) => [...queryKeys.research.all, "results", id] as const,
        history:     () => [...queryKeys.research.all, "history"] as const,
    },
    analytics: {
        all:         ["analytics"] as const,
        telemetry:   () => [...queryKeys.analytics.all, "telemetry"] as const,
        metrics:     () => [...queryKeys.analytics.all, "metrics"] as const,
    },
    governance: {
        all:         ["governance"] as const,
        policies:    () => [...queryKeys.governance.all, "policies"] as const,
        audit:       () => [...queryKeys.governance.all, "audit"] as const,
        logs:        () => [...queryKeys.governance.all, "logs"] as const,
    },
    browser: {
        all:         ["browser"] as const,
        sessions:    () => [...queryKeys.browser.all, "sessions"] as const,
        screenshot:  (id: string) => [...queryKeys.browser.all, "screenshot", id] as const,
    },
    computer: {
        all:         ["computer"] as const,
        status:      () => [...queryKeys.computer.all, "status"] as const,
        actions:     () => [...queryKeys.computer.all, "actions"] as const,
    },
    dashboard: {
        all:         ["dashboard"] as const,
        overview:    () => [...queryKeys.dashboard.all, "overview"] as const,
        health:      () => [...queryKeys.dashboard.all, "health"] as const,
        resources:   () => [...queryKeys.dashboard.all, "resources"] as const,
        timeline:    () => [...queryKeys.dashboard.all, "timeline"] as const,
        agents:      () => [...queryKeys.dashboard.all, "agents"] as const,
        events:      () => [...queryKeys.dashboard.all, "events"] as const,
        header:      () => [...queryKeys.dashboard.all, "header"] as const,
        deployChecks: () => [...queryKeys.dashboard.all, "deployChecks"] as const,
        flakyTests:  () => [...queryKeys.dashboard.all, "flakyTests"] as const,
        rollbacks:   () => [...queryKeys.dashboard.all, "rollbacks"] as const,
        incidents:   () => [...queryKeys.dashboard.all, "incidents"] as const,
        credentials: () => [...queryKeys.dashboard.all, "credentials"] as const,
        rootCause:   () => [...queryKeys.dashboard.all, "rootCause"] as const,
        vulnerabilities: () => [...queryKeys.dashboard.all, "vulnerabilities"] as const,
        branchProtection: () => [...queryKeys.dashboard.all, "branchProtection"] as const,
    },
    settings: {
        all:         ["settings"] as const,
        config:      () => [...queryKeys.settings.all, "config"] as const,
        preferences: () => [...queryKeys.settings.all, "preferences"] as const,
    },
    intelligence: {
        all:             ["intelligence"] as const,
        intent:          (id: string) => [...queryKeys.intelligence.all, "intent", id] as const,
        analysis:        (id: string) => [...queryKeys.intelligence.all, "analysis", id] as const,
        assessment:      (id: string) => [...queryKeys.intelligence.all, "assessment", id] as const,
        preview:         (id: string) => [...queryKeys.intelligence.all, "preview", id] as const,
        strategy:        (id: string) => [...queryKeys.intelligence.all, "strategy", id] as const,
        plan:            (id: string) => [...queryKeys.intelligence.all, "plan", id] as const,
        capabilities:    (id: string) => [...queryKeys.intelligence.all, "capabilities", id] as const,
        risks:           (id: string) => [...queryKeys.intelligence.all, "risks", id] as const,
        graph:           (id: string) => [...queryKeys.intelligence.all, "graph", id] as const,
        report:          (id: string) => [...queryKeys.intelligence.all, "report", id] as const,
    },
    missionControl: {
        all:         ["missionControl"] as const,
        mission:     (id: string) => [...queryKeys.missionControl.all, "mission", id] as const,
        missions:    () => [...queryKeys.missionControl.all, "missions"] as const,
        status:      (id: string) => [...queryKeys.missionControl.all, "status", id] as const,
        activity:    (id: string) => [...queryKeys.missionControl.all, "activity", id] as const,
        timeline:    (id: string) => [...queryKeys.missionControl.all, "timeline", id] as const,
    },
    connectors: {
        all:            ["connectors"] as const,
        list:           () => [...queryKeys.connectors.all, "list"] as const,
        detail:         (type: string) => [...queryKeys.connectors.all, "detail", type] as const,
        health:         (type: string) => [...queryKeys.connectors.all, "health", type] as const,
        activity:       (type: string) => [...queryKeys.connectors.all, "activity", type] as const,
    },
    executiveDashboard: {
        all:     ["executiveDashboard"] as const,
        data:    () => [...queryKeys.executiveDashboard.all, "data"] as const,
    },
    analyticsDashboard: {
        all:     ["analyticsDashboard"] as const,
        data:    () => [...queryKeys.analyticsDashboard.all, "data"] as const,
    },
    enterpriseCognition: {
        all:     ["enterpriseCognition"] as const,
    },
    execution: {
        all:         ["execution"] as const,
        dashboard:   () => [...queryKeys.execution.all, "dashboard"] as const,
        list:        () => [...queryKeys.execution.all, "list"] as const,
        detail:      (id: string) => [...queryKeys.execution.all, "detail", id] as const,
    },
}
